(function(){

	window.MessageData = {
		faqList:[{
			nickname:'Linuct',
			question:"你们那里还招人吗？很想从事这个行业",
			createDateTime:"2013-09-19",
			answer:"详细信息见公司网站上的招聘海报"
		},{
			nickname:'Linuct',
			question:"你们那里还招人吗？很想从事这个行业",
			createDateTime:"2013-09-19",
			answer:"详细信息见公司网站上的招聘海报"
		},{
			nickname:'Linuct',
			question:"你们那里还招人吗？很想从事这个行业",
			createDateTime:"2013-09-19",
			answer:"详细信息见公司网站上的招聘海报"
		},{
			nickname:'Linuct',
			question:"你们那里还招人吗？很想从事这个行业",
			createDateTime:"2013-09-19",
			answer:"详细信息见公司网站上的招聘海报"
		},{
			nickname:'Linuct',
			question:"你们那里还招人吗？很想从事这个行业",
			createDateTime:"2013-09-19",
			answer:"详细信息见公司网站上的招聘海报"
		},{
			nickname:'Linuct',
			question:"你们那里还招人吗？很想从事这个行业",
			createDateTime:"2013-09-19",
			answer:"详细信息见公司网站上的招聘海报"
		},{
			nickname:'Linuct',
			question:"你们那里还招人吗？很想从事这个行业",
			createDateTime:"2013-09-19",
			answer:"详细信息见公司网站上的招聘海报"
		}],
		messageList:{
			counts:6,
			list:[{
				nickname:'Linuct',
				content:"你们那里还招人吗？很想从事这个行业",
				createDateTime:"2013-09-19",
				replyContent:"详细信息见公司网站上的招聘海报",
				replyDateTime:"2013-09-19"
			},{
				nickname:'Linuct',
				content:"你们那里还招人吗？很想从事这个行业",
				createDateTime:"2013-09-19",
				replyContent:"详细信息见公司网站上的招聘海报",
				replyDateTime:"2013-09-19"
			},{
				nickname:'Linuct',
				content:"你们那里还招人吗？很想从事这个行业",
				createDateTime:"2013-09-19",
				replyContent:"详细信息见公司网站上的招聘海报",
				replyDateTime:"2013-09-19"
			},{
				nickname:'Linuct',
				content:"你们那里还招人吗？很想从事这个行业",
				createDateTime:"2013-09-19",
				replyContent:"详细信息见公司网站上的招聘海报",
				replyDateTime:"2013-09-19"
			},{
				nickname:'Linuct',
				content:"你们那里还招人吗？很想从事这个行业",
				createDateTime:"2013-09-19",
				replyContent:"详细信息见公司网站上的招聘海报",
				replyDateTime:"2013-09-19"
			},{
				nickname:'Linuct',
				content:"你们那里还招人吗？很想从事这个行业",
				createDateTime:"2013-09-19",
				replyContent:"详细信息见公司网站上的招聘海报",
				replyDateTime:"2013-09-19"
			},{
				nickname:'Linuct',
				content:"你们那里还招人吗？很想从事这个行业",
				createDateTime:"2013-09-19",
				replyContent:"详细信息见公司网站上的招聘海报",
				replyDateTime:"2013-09-19"
			},{
				nickname:'Linuct',
				content:"你们那里还招人吗？很想从事这个行业",
				createDateTime:"2013-09-19",
				replyContent:"详细信息见公司网站上的招聘海报",
				replyDateTime:"2013-09-19"
			}]
		}
	};

	window.AboutData = {
		data:{
			image:'images/fullsize/archival.jpg',
			content:'蒂芙尼从大自然中吸取灵感，并从大自然的丰富宝藏中寻找赋予设计作品生命力的珍贵材质。蒂芙尼相信协力维护带给我们无穷灵感的自然之美是公司应尽的道德义务。',
			videoUrl:'http://player.youku.com/player.php/Type/Folder/Fid/20115246/Ob/1/sid/XNjEyNjExODgw/v.swf'
		}
	};

	window.GalleryData = {
		data:[{
			videoUrl:'http://player.youku.com/player.php/sid/XNjExODQxOTY0/v.swf',
			detailImage:'',
			image:'images/fullsize/king.jpg',
			title:'钻石之王'
		},{
			videoUrl:'',
			detailImage:'images/fullsize/_1.png',
			image:'images/fullsize/archival.jpg',
			title:'钻石之王'
		},{
			videoUrl:'',
			detailImage:'images/fullsize/_1.png',
			image:'images/fullsize/bluebook.jpg',
			title:'设计先锋'
		},{
			videoUrl:'http://player.youku.com/player.php/sid/XNjA3ODk1MTU2/v.swf',
			detailImage:'',
			image:'images/fullsize/intro.jpg',
			title:'光彩夺目的发现'
		},{
			videoUrl:'',
			detailImage:'images/fullsize/_1.png',
			image:'images/fullsize/box.jpg',
			title:'光彩夺目的发现'
		},{
			videoUrl:'',
			detailImage:'images/fullsize/_1.png',
			image:'images/fullsize/celeb.jpg',
			title:'从星云集'
		},{
			videoUrl:'http://player.youku.com/player.php/sid/XNjEyNzcyOTYw/v.swf',
			detailImage:'',
			image:'images/fullsize/gemstone.jpg',
			title:'蒂芙尼蓝色礼盒'
		},{
			videoUrl:'',
			detailImage:'images/fullsize/_1.png',
			image:'images/fullsize/history.jpg',
			title:'蒂芙尼蓝色礼盒'
		},{
			videoUrl:'',
			detailImage:'images/fullsize/_1.png',
			image:'images/fullsize/pioneer_brooch.jpg',
			title:'体育奖杯'
		},{
			videoUrl:'',
			detailImage:'images/fullsize/_1.png',
			image:'images/fullsize/pioneer_peretti.jpg',
			title:'美丽创新'
		},{
			videoUrl:'',
			detailImage:'images/fullsize/_1.png',
			image:'images/fullsize/rubedo.jpg',
			title:'钻石之王'
		},{
			videoUrl:'',
			detailImage:'images/fullsize/_1.png',
			image:'images/fullsize/surprises.jpg',
			title:'钻石之王'
		},{
			videoUrl:'',
			detailImage:'images/fullsize/_1.png',
			image:'images/fullsize/trophies.jpg',
			title:'钻石之王'
		}]
	}
})()